backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
    - name: "arbi"
    label: "আরবি লেসন"
    folder: "content/arbi"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
            - {label: "শিরোনাম", name: "title", widget: "string"}
            - {label: "প্রকাশের তারিখ", name: "date", widget: "datetime"}
            - {label: "লেবেল/ট্যাগ", name: "tags", widget: "list", required: false}
            - {label: "কনটেন্ট", name: "body", widget: "markdown"}
            - {label: "PDF লিংক", name: "pdf_link", widget: "string", required: false}

    - name: "blog"
    label: "ব্লগ"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
            - {label: "শিরোনাম", name: "title", widget: "string"}
            - {label: "প্রকাশের তারিখ", name: "date", widget: "datetime"}
            - {label: "লেখক", name: "author", widget: "string"}
            - {label: "কনটেন্ট", name: "body", widget: "markdown"}

    - name: "bibidh"
    label: "বিবিধ"
    folder: "content/bibidh"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
            - {label: "শিরোনাম", name: "title", widget: "string"}
            - {label: "প্রকাশের তারিখ", name: "date", widget: "datetime"}
            - {label: "কনটেন্ট", name: "body", widget: "markdown"}

    - name: "lifestyle"
    label: "লাইফস্টাইল"
    folder: "content/lifestyle"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
            - {label: "শিরোনাম", name: "title", widget: "string"}
            - {label: "প্রকাশের তারিখ", name: "date", widget: "datetime"}
            - {label: "কনটেন্ট", name: "body", widget: "markdown"}

    - name: "notice"
    label: "নোটিশ"
    folder: "content/notice"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
            - {label: "শিরোনাম", name: "title", widget: "string"}
            - {label: "প্রকাশের তারিখ", name: "date", widget: "datetime"}
            - {label: "কনটেন্ট", name: "body", widget: "markdown"}